### ISSUE TITLE
Doesn't seem to be working?

### ISSUE THREAD

**Issue by farzadmf** [gsuuon/tshjkl.nvim#2]
Hi, I'm trying to install the plugin using `lazy.nvim` with the following setup:
```lua
keys = {
  { '<leader>ct', desc = 'toggle tsjhkl' },
},
opts = {
  keymaps = {
    toggle = '<leader>ct',
  },
}
```

Now, when I press `<leader>ct` _something_ happens: seems like the current node (maybe it's the current node, but not sure TBH) is selected, but when I press `h`, it goes out of visual mode and cursor jumps "somewhere" (couldn't figure out where exactly it's trying to jump). Or when I press `l`, _nothing_ happens.

**Comment by gsuuon** [comment]
Hi! What's the text you're seeing this on? Do you see this with the default options?

**Comment by gsuuon** [comment]
@farzadmf Let me know if you still see the issue!

**Comment by farzadmf** [comment]
Thank you @gsuuon, seems to do something now.

However, I'm still confused; let's say I'm working with this:
```lua
M.spec = {
  url = 'https://github.com/linty-org/readline.nvim',
  name = 'readline.nvim',
  dependencies = {
    require('plugins._deps.vim-rsi').spec,
  },
}
```
- I go on `name` and trigger the plugin.
- I press `l`; nothing happens.
- I press `h`; it selects ` name = 'readline.nvim'`, which is confusing; I thought that should be the job of `l` (somehow going to "the right").
- I press `j` and nothing happens.
- I press `k` and `readline.nvim` is selected.

So, it seems like the bindings are working in a way that's unintuitive for me. But it's VERY likely that it's because I don't know how nodes work in Treesitter.

**Comment by gsuuon** [comment]
`h` goes left and `l` goes right is the correct intuition. Pressing `l` does nothing because you're already at the innermost (right-most) node, and `h` brings you out / to the left because indentation typically indicates going deeper in. The highlighting is meant to help show the current context, so the entire parent node is `Comment` by default and siblings are highlighted `WarningFloat` and `InfoFloat` to show you where you would go with `j` and `k`. You should be able to just swap `h` and `l` if that makes more sense to you, but I'd give the `h` goes out and `l` goes in a bit of a try first before changing. It helps if you think of ts nodes as a tree, (or check out `:TSPlaygroundToggle`)

@farzadmf just a heads up, I think I may need to update how this plugin works with lazy.nvim again as the lazy-loading doesn't do what I thought it did

**Comment by farzadmf** [comment]
> as the lazy-loading doesn't do what I thought it did

Nice, going to try it after that. Maybe that's why it's a bit unintuitive for me :thinking:
